# Generated by Django 5.2.3 on 2025-07-01 21:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_description_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(django.db.models.functions.text.MD5('description'), name='product_description_idx'),
        ),
    ]
